project_id = "cituuejbtwrwarjmttwt"

[functions.send-contact-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.broadcast-message]
verify_jwt = false
